### ISSUE TITLE
SDSoC fail to run

### ISSUE THREAD

**Issue by xiemark** [natsutan/cocytus#9]
When I try to run tiny-yolo on Xilinx ZCU102 FPGA, it failed with the error message,
.....
ERROR: No virtual to physical mapping found; Make sure all arrays passed to the
zero copy datamover are allocated with sds_alloc
Segmentation fault

It seems the memory allocation for SDSoC failed.
The memory used is too large for SDSoC to allocate.

**Comment by natsutan** [comment]
I'm sorry. Development on this project has been stopped.

New project is this. But, Qumico is not support sdsoc.
https://github.com/PasonaTech-Inc/Qumico

Thank you.

**Comment by xiemark** [comment]
Thank you for your quick answer!
